[template]
src = "imageserv/cantaloupe.properties.tpl"
dest = "/usr/local/cantaloupe/cantaloupe.properties"
uid = 1000
gid = 1000
mode = "0644"
keys = [
  "/cantaloupe/admin/interface/enable",
  "/cantaloupe/admin/user",
  "/cantaloupe/admin/pass",
]
